# Images

## Introduction to Digital Images

Digital images are stored as a grid (matrix) of colored dots called **pixels**. Each pixel typically has three primary color values:

- **Red**
- **Green**
- **Blue**

Hence, in code, an RGB image can be considered a 3D array (list) with dimensions corresponding to `(height, width, channels)`. For instance, a 640×480 image has 640 pixels in width (horizontal) and 480 in height (vertical), each pixel containing an `(R, G, B)` triplet.

Sometimes, there's an **Alpha** channel (RGBA) representing transparency. We’ll focus on standard RGB for simplicity.

In Python, the **Pillow** library (PIL) is a common tool for reading and writing these images, while libraries like [**diffusers**](https://github.com/huggingface/diffusers) offer utility functions (like `load_image`) for convenience.

We’ll explore both **Pillow**, **numpy** and **diffusers** for:

1. Loading images
2. Manipulating images
3. Creating simple animations (MP4s)

Let’s start by installing and importing the necessary libraries.

We will install all necessary libraries in one step using **pip** like discussed in previous chapters:

`pip install pillow numpy diffusers tqdm`

## Loading Images

There are multiple ways in different libraries to load images stored locally on our device. The most common way is to load it using Pillow (a fort of PIL). See [readthedocs.io](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html) and [automate the boring stuff](https://automatetheboringstuff.com/chapter17/) for more.

In [5]:
from PIL import Image # Import the Image class

img = Image.open("sample.jpg")

We can inspect the loaded image like so:

In [6]:
print('size:', img.size)
print('mode:', img.mode)
print('format:', img.format)

size: (512, 512)
mode: RGB
format: JPEG


To display an image, we can use the show method, which will open the image in the default image-viewer:

In [7]:
img.show()

### Loading from the Web

`Image.open` will only work with local files and return a `PIL`. The `diffusers` library provides a helper function to load images from the web (via ursl) or from disk (using paths).

In [8]:
from diffusers.utils import load_image

img = load_image("https://thispersondoesnotexist.com/")

The resulting image will be in the `PIL` format aswell.

### Saving images

Images loaded in the `PIL` format can be saved locally with a call to `save` which takes a path as the parameter. If no format is provided it will be chosen according to the file-extension in the path.

In [9]:
from diffusers.utils import load_image

img = load_image("https://thispersondoesnotexist.com/")

img.save("face1.png", format="PNG") # Explicit PNG

img.save("face2.png") # Implicit PNG


## Manipulating Images

Pillow provides many methods for image manipulation. Here are some common ones:

1. **Rotate**: `image.rotate(angle, expand=True)`.
2. **Resize (Scale)**: `image.resize((new_width, new_height))`.
3. **Blur**: using `ImageFilter.BLUR` or other filters from `ImageFilter`.
4. **Enhance Contrast**: using `ImageEnhance.Contrast(image)`.
5. **Composite**: combine multiple images using `Image.composite`.

We'll demonstrate these on an example image.

In [10]:
from diffusers.utils import load_image

img = load_image("https://thispersondoesnotexist.com/")

# 1. Rotate
rotated_image = img.rotate(45, expand=True)
rotated_image.save("img/rotated.png")

![rotated](img/rotated.png)

In [11]:
# 2. Scale
width, height = img.size
half_sized_image = img.resize((width // 2, height // 2))
half_sized_image = img.save("img/scaled.png")

![rotated](img/scaled.png)

In [12]:
# 3. Blur
from PIL import ImageFilter
blurred_image = img.filter(ImageFilter.BLUR)
blurred_image.save("img/blurred.png")

![rotated](img/blurred.png)

In [13]:
# 4. Enhance Contrast
from PIL import ImageEnhance
enhancer = ImageEnhance.Contrast(img)
contrast_image = enhancer.enhance(2.0)  # Increase contrast
contrast_image.save("img/enhanced.png")

![rotated](img/enhanced.png)

In [14]:
# 5. Composite
# For demonstration, we composite the original and blurred image using a gradient mask.
mask = Image.linear_gradient("L").resize(img.size)
img_rgba = img.convert("RGBA")
blurred_rgba = blurred_image.convert("RGBA")
composited_img = Image.composite(img_rgba, blurred_rgba, mask)
composited_img.save("img/composited.png")

![composited](img/composited.png)

In [15]:
# 6. Crop
cropped = img.crop((0, 0, 256, 50))
cropped.save("img/cropped.png")

![cropped](img/cropped.png)

### Loading Images as numpy

We can also use numpy to read an image direclty as a three-dimensional list of color values. for that we can convert any `PIL` image to `numpy`.

In [16]:
from diffusers.utils import load_image
import numpy as np # numpy is usually renamed to np

# Load as PIL
img_pil = load_image("https://thispersondoesnotexist.com/")


# convert to numpy
img_np = np.asarray(img_pil)
print('dimensions:', img_np.ndim)
print('shape:', img_np.shape)
print('size', img_np.size)

dimensions: 3
shape: (1024, 1024, 3)
size 3145728


In [17]:
print(img_np)

[[[162 156 168]
  [161 157 171]
  [154 153 169]
  ...
  [162 158 172]
  [165 154 170]
  [160 145 164]]

 [[163 159 174]
  [157 154 171]
  [153 154 172]
  ...
  [158 158 170]
  [164 157 173]
  [166 157 174]]

 [[159 157 178]
  [153 154 174]
  [154 155 173]
  ...
  [160 162 174]
  [164 163 177]
  [164 162 176]]

 ...

 [[126 126 154]
  [129 131 154]
  [128 133 153]
  ...
  [128 134 156]
  [128 134 156]
  [130 137 156]]

 [[130 126 153]
  [128 128 152]
  [130 135 155]
  ...
  [128 134 156]
  [132 134 155]
  [137 138 159]]

 [[138 132 158]
  [127 127 151]
  [125 131 153]
  ...
  [130 137 156]
  [142 143 164]
  [148 143 166]]]


We can now manipulate pixel values directly using mathematical functions, but we can also use generative artificial intelligence to write the functions for us. For that we will just need to formulate our prompt accordingly.

As a base prompt we can use the following:

`Give me a python function that takes an image in numpy format (RGB) and manipulates it. The function should return a numpy array in the same format and be called my_function. The function should ...`

Using this prompt and descriptions for what should happen with the image we can manipulate without writing the code ourselves.

For example:

`The function should make the image grayscale.`

`The function should invert the image.`

`The function should sort pixels in the image by brightness.`

Paste the resulting funtion into your code and execute it.

In [18]:
from diffusers.utils import load_image

# Paste your function here:

def my_function(img):
    return img

img_pil = load_image("https://thispersondoesnotexist.com/")
img_np = np.asarray(img_pil)

manipulated_img = my_function(img_np)

Image.fromarray(manipulated_img).save("img/manipulated.png")

## Building a Simple Dynamical System with Image Filters

A **dynamical system** evolves over time by repeatedly applying the same (or similar) rules. Here, we’ll apply filters (blur, sharpen, rotate, etc.) in a loop, treating each new image as the input for the next iteration.

**Learn more**: [Reaction–diffusion systems](https://en.wikipedia.org/wiki/Reaction–diffusion_system)

In [ ]:
from diffusers.utils import export_to_gif
from tqdm import tqdm

# 2. Load a base image
img = load_image("https://thispersondoesnotexist.com/").convert("RGB")

# 3. Iteratively apply transformations
num_frames = 60
frames = []

for i in tqdm(range(num_frames)):
    img = img.filter(ImageFilter.BLUR)
    img = img.filter(ImageFilter.SHARPEN)
    frames.append(img)
    
export_to_gif(frames, "system.gif", fps=10)

100%|██████████| 60/60 [00:02<00:00, 28.05it/s]


'system.gif'

![System](system.gif)

In [31]:
from diffusers.utils import export_to_gif
from tqdm import tqdm

# 2. Load a base image
img = load_image("https://thispersondoesnotexist.com/").convert("RGB")

# 3. Iteratively apply transformations
num_frames = 60
frames = []

for i in tqdm(range(num_frames)):
    img = img.filter(ImageFilter.GaussianBlur(radius=4))
 
    # use a fixed sharpen amount (or vary it too)
    img = img.filter(ImageFilter.UnsharpMask(radius=10, percent=550, threshold=1))
    frames.append(img)
    
export_to_gif(frames, "system2.gif", fps=10)

100%|██████████| 60/60 [00:02<00:00, 21.64it/s]


'system2.gif'

![System](system2.gif)

### Example: Repeated Blur + Sharpen + Rotation
We’ll do the following:
1. Load an initial image.
2. Rotate it slightly, then blur and sharpen.
3. Save each iteration.
4. Export all frames as an GIF using `export_to_gif`.

In [19]:
from diffusers.utils import export_to_gif
from tqdm import tqdm

# 1. Define the transformation steps
def blur_then_sharpen(input_image: Image.Image) -> Image.Image:
    blurred = input_image.filter(ImageFilter.BLUR)
    sharpened = blurred.filter(ImageFilter.SHARPEN)
    return sharpened

# 2. Load a base image
original_img = load_image("https://thispersondoesnotexist.com/").convert("RGB")


# 3. Iteratively apply transformations
num_frames = 60
frames = []

current_img = original_img
angle = 0

for i in tqdm(range(num_frames), desc="Generating frames"):
    # Rotate slightly
    rotated = current_img.rotate(angle, expand=True)

    # Blur + Sharpen
    processed = rotated.filter(ImageFilter.BLUR).filter(ImageFilter.SHARPEN)

    # Resize back to original shape if rotation changed dimensions
    processed = processed.resize(original_img.size)

    # Accumulate frames
    frames.append(processed)

    # Prepare next iteration
    current_img = processed
    angle += 1  # 1 degree each iteration

Generating frames: 100%|██████████| 60/60 [00:04<00:00, 13.49it/s]


### Exporting the Frames as an MP4
We can now call `export_to_video` to compile these frames into a video file.

In [23]:
export_to_gif(
    frames,
    output_gif_path="animation.gif",
    fps=10,
)


'animation.gif'

![Animation](animation.gif)